### PR TITLE
Added support for Debian

### PR DESCRIPTION
**Pull request by bplower**
The include task for installing OS specific packages has been changed to import the file based on the value of the OS family, so `install_os_packages.yml` was renamed to `install_RedHat_packages.yml`. Additionally, the variable files for each OS includes the variable `pypi_server_bin` to represent the path for the 'pypi-server' executable. This was needed for the systemd service template, since pypi-server is installed to different locations on the different OSs. An additional test for the Debian platform was added, and documentation was updated to include the reference to the debian/jessie64 test.

### CODE REVIEW

**Comment by elliotweiser** [comment]
@bplower Thanks for the PR! Overall it looks fine to me, but I'd like to molecule test it before giving my final 👍 . I also pulled in @skippyPeanutButter because I'd like his review as well. We'll get back to you shortly.

**Comment by skippyPeanutButter** [comment]
@bplower Thanks for the contribution, I'll test and review this change sometime today.

**Comment by bplower** [comment]
Sounds good! Let me know if you guys have any questions or concerns

**Comment by skippyPeanutButter** [comment]
Clearly when I said sometime today, I meant a few days from now :man_facepalming: .
Thanks for your patience, your change was tested and it looks good.

**Pull request merged**
